apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.10
        ports:
        - containerPort: 3306 