apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - https://raw.githubusercontent.com/keycloak/keycloak-quickstarts/20.0.1/kubernetes-examples/keycloak.yaml
  - db.yaml
  - db-svc.yaml