apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  template:
    spec:
      containers:
        - args:
            - start-dev
          env:
            - name: KEYCLOAK_ADMIN
              value: ""
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: kcadmin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: ""
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: kcpassword
          name: keycloak