apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-keycloak

bases:
  - ../../base/

resources:
  - namespace.yaml
  - ingress.yaml
  - pv.yaml
  - pvc.yaml

patches:
  - db-patch.yaml
  - keycloak-patch.yaml
