apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-keycloack-database
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/pv/dev-keycloak-database"