apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-keycloack-themes
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/pv/dev-keycloak-themes"